users:
    title: Users
    fields:
        - {id: name, title: Name, type: char}
        - {id: paycheck, title: Sallary, type: int}
        - {id: date_joined, title: Date of joined, type: date}
rooms:
    title: Rooms
    fields:
        - {id: department, title: Department, type: char}
        - {id: spots, title: Spots, type: int}
books:
    title: Books
    fields:
        - {id: b_title, title: Book title, type: char}
        - {id: author, title: Author, type: char}
        - {id: isbn, title: ISBN, type: int}
        - {id: number_of_pages, title: Number of pages, type: int}